services:
  front:
    container_name: transcendence-front
    build:
      dockerfile: docker/proxy/Dockerfile
      context: ../../
    ports:
      - ${OUT_PORT}:443
    volumes:
      - log-nginx:/var/log/front
    environment:
      - TZ=Europe/Paris
    depends_on:
      user-api:
        condition: service_started
      auth-api:
        condition: service_started
    healthcheck:
      disable: true
    networks:
      - front
    restart: unless-stopped
