FROM		owasp/modsecurity-crs:nginx-alpine

RUN			mkdir -p /etc/nginx/modsecurity.d \
			&& cp /etc/modsecurity.d/unicode.mapping /etc/nginx/modsecurity.d/unicode.mapping

COPY		docker/proxy/config/default.prod.conf.template \
			/etc/nginx/templates/conf.d/default.conf.template

USER		root
RUN			mkdir -p /var/log/front
RUN			touch /var/log/front/err.log /var/log/front/log.log
RUN			chmod -R 777 /var/log/front
USER		nginx

EXPOSE		80 443
STOPSIGNAL	SIGINT
