services:
  front:
    container_name: transcendence-front
    build:
      dockerfile: docker/front/Dockerfile
      context: ../../
    ports:
      - ${OUT_PORT}:443
    environment:
      - SERVER_NAME=localhost
      - TZ=Europe/Paris
    depends_on:
      user-api:
        condition: service_started
      auth-api:
        condition: service_started
    networks:
      - front
    restart: unless-stopped
