services:
  webserv:
    container_name: transcendence-webserv
    build:
      dockerfile: docker/front/Dockerfile
      context: ../../
      args:
        - VITE_USER_URL=${VITE_USER_URL}
        - VITE_AUTH_URL=${VITE_AUTH_URL}
    environment:
      - TZ=Europe/Paris
    networks:
      - front
    restart: unless-stopped
