services:
  webserv:
    container_name: transcendence-webserv
    build:
      dockerfile: docker/front/Dockerfile
      context: ../../
    environment:
      - TZ=Europe/Paris
    networks:
      - front
    restart: unless-stopped
