services:
  front:
    image: owasp/modsecurity-crs:nginx-alpine
    ports:
      - 443:443
    # environment:
    #   - euuuh
  user-api:
    build:
      dockerfile: docker/user-api/Dockerfile
      context: ..
    networks:
      - transcendence
    ports:
      - 3000:3000

networks:
  transcendence:
    external: false
    name: transcendence
