global:
  scrape_interval: 5s

alerting:
  alertmanagers:
    - static_configs:
      - targets:
        - transcendence-alert:9093

scrape_configs:
  - job_name: 'prometheus'
    metrics_path: '/prometheus/metrics'
    basic_auth:
      username: admin
      password: PROM_ADMIN_PASSWD
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']
  
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'nodejs'
    static_configs:
      - targets: ['transcendence-api-auth:3000']
      - targets: ['transcendence-api-user:3000']
