global:
  scrape_interval: 30s

# alerting:
#   alertmanagers:
#     - static_configs:
#       - targets:
#         - alertmanager:9093

scrape_configs:
  - job_name: 'prometheus'
    metrics_path: '/prometheus/metrics'
    basic_auth:
      username: admin
      password: PROM_ADMIN_PASSWD
    static_configs:
      - targets: ['localhost:9090']
